added footer to belgium, fixed minor issues in labels
nss-day-cohort-47/hello-world-perfect-plutonians pull request #11
Opened 2021-02-23 22:02 UTC by prestonshotts

yeehaw

2021-02-23 22:03 UTC, D-Upchurch approved these changes
excellent day of progress

2021-02-24 02:58 UTC, D-Upchurch requested changes
Middle column on country pages aren't wrapping properly when browser is scaled down

2021-02-24 15:24 UTC, D-Upchurch approved these changes

2021-02-24 15:25 UTC, JSchugt approved these changes
Ship it.

2021-02-24 15:30 UTC, merged